controllers/DefaultController.php
<?php

namespace saghar\address\controllers;

use aminkt\widgets\alert\Alert;
use saghar\address\models\Address;
use saghar\address\models\City;
use saghar\address\models\State;
use yii\data\ActiveDataProvider;
use yii\db\StaleObjectException;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * Default controller for the `addressManager` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index view for the module to show list of addresses, create and update actions.
     *
     * @param null|integer $id If trying to update an address this arg will find that address.
     *
     * @return string
     *
     * @throws \yii\web\NotFoundHttpException
     *
     * @author Saghar Mozhdehi
     * @author Amin Keshavarz <amin@keshavarz.pro>
     */
    public function actionIndex($id = null)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Address::find()
        ]);

        if ($id) {
            $model = Address::findOne($id);
            if (!$model) {
                throw new NotFoundHttpException("آدرس مورد نظر یافت نشد.");
            }
        } else {
            $model = new Address();
        }
        if (\Yii::$app->getRequest()->isPost) {
            try {
                if ($model->isNewRecord) {
                    $address = Address::create(\Yii::$app->getRequest()->post('Address'));
                } else {
                    $address = Address::edit($id, \Yii::$app->getRequest()->post('Address'));
                }

                return $this->redirect(['index']);
            } catch (\RuntimeException $exception) {
                Alert::error("خطا در ثبت اطلاعات", "آدرس ذخیره نشد. دوباره تلاش کنید.");
            }
        }

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'model' => $model
        ]);
    }


    /**
     * Delete address
     * @param $id
     * @throws NotFoundHttpException
     */
    public function actionDelete($id)
    {
        $address = Address::findOne($id);
        if ($address) {
            try {
                $address->delete();
                \Yii::$app->getSession()->setFlash("success", "آدرس حذف شد");
                $this->redirect('index');
            } catch (\Exception $e) {
                \Yii::error($e->getMessage());
                Alert::error('خطا در انجام عملیات', 'دسته مورد نظر حذف نشد');
            }
        } else {
            throw new NotFoundHttpException("آدرس پیدا نشد");
        }
    }

    /**
     * View Address
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $address = Address::findOne($id);
        if ($address) {
            return $this->render('view_address', [
                "model" => $address
            ]);
        } else {
            throw new NotFoundHttpException("آدرس پیدا نشد");
        }
    }
}

views/default/_form.php
<?php
/** @var \yii\web\View $this */

use yii\web\JsExpression;

/** @var \saghar\address\models\Address $model */

$url = \yii\helpers\Url::to(['/address/default/get-cities'], true);
$this->title = "ثبت آدرس جدید"
?>
<div class="addressManager-form">
    <?php $form = \yii\widgets\ActiveForm::begin(['method' => 'post']); ?>

    <?php
    $cities = \saghar\address\models\City::find()->all();
    $cities = \yii\helpers\ArrayHelper::map($cities, 'id', 'name', 'stateName');

    echo $form->field($model, 'cityId')->widget(\kartik\select2\Select2::className(), [
        'data' => $cities,
        'options' => ['placeholder' => 'شهر را انتخاب کنید ...'],
        'pluginOptions' => [
            'allowClear' => true
        ]
    ]);
    ?>

    <?= $form->field($model, 'address')->textarea() ?>

    <?= $form->field($model, 'zipCode')->textInput() ?>

    <?= $form->field($model, 'latitude')->hiddenInput(['id' => 'us2-lat'])->label(false) ?>
    <?= $form->field($model, 'longitude')->hiddenInput(['id' => 'us2-lon'])->label(false) ?>

    Location: <input type="text" id="us2-address" style="width: 200px"/>
    <br>

    <?php
    echo \pigolab\locationpicker\LocationPickerWidget::widget([
        'key' => 'AIzaSyBjFztI9oEaunJToOiAQ9lSS8Bfbre3BNo',	// require , Put your google map api key
        'options' => [
            'style' => 'width: 100%; height: 400px', // map canvas width and height
        ] ,
        'clientOptions' => [
            'location' => [
                'latitude'  => 37.28083300 ,
                'longitude' => 49.58305600,
            ],
            'addressFormat' => 'street_number',
            'inputBinding' => [
                'latitudeInput'     => new JsExpression("$('#us2-lat')"),
                'longitudeInput'    => new JsExpression("$('#us2-lon')"),
                'locationNameInput' => new JsExpression("$('#us2-address')")
            ],

        ]
    ]);
    ?>

    <?= \yii\helpers\Html::submitButton($model->isNewRecord ? "ذخیره" : "ویرایش", [
        'class' => 'btn btn-primary'
    ]) ?>

    <?php \yii\widgets\ActiveForm::end(); ?>
</div>

views/default/index.php
<?php
/** @var \yii\web\View $this
/** @var \yii\data\ActiveDataProvider $dataProvider
 * @var \saghar\address\models\Address $model
 */

$this->title = "آدرس های ثبت شده";
?>
<div class="addressManager-default-index">
    <h1><?= $this->title ?></h1>
    <div class="row">
        <div class="col-md-8">
            <?= \yii\grid\GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => "",
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    [
                        'attribute' => 'countryName',
                    ],
                    [
                        'attribute' => 'stateName',
                    ],
                    [
                        'attribute' => 'cityName',
                    ],
                    [
                        'attribute' => 'address'
                    ],
                    [
                        'label' => 'تاریخ',
                        'format' => 'raw',
                        'value' => function ($model) {
                            /** @var \saghar\address\models\Address $model */
                            $updateDate = Yii::$app->getFormatter()->asDatetime($model->updateAt);
                            $createDate = Yii::$app->getFormatter()->asDatetime($model->updateAt);
                            $html = <<<HTML
تاریخ ویرایش : $updateDate <br>
 تاریخ ایجاد : $createDate
HTML;
                            return $html;
                        }
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'urlCreator' => function ($action, $model, $key, $index) {
                            if ($action === 'update') {
                                return \yii\helpers\Url::to(['default/index', 'id' => $model->id]);
                            }
                            if ($action === 'delete') {
                                return \yii\helpers\Url::to(['default/delete', 'id' => $model->id]);
                            }
                            if ($action == 'view') {
                                return \yii\helpers\Url::to(['default/view', 'id' => $model->id]);
                            }
                        }
                    ],
                ]
            ]); ?>
        </div>
        <div class="col-md-4">
            <?php
            echo $this->render('_form', ['model' => $model]);
            ?>
        </div>
    </div>
</div>

views/default/view_address.php
<?php /** @var \saghar\address\models\Address $model */ ?>


<p>
    <?=
    yii\widgets\DetailView::widget([
        'model' => $model,
        'attributes' => [
            'address' => [
                'label' => 'آدرس',
                'value' => $model->address
            ],
            'zipCode' => [
                'label' => 'کد پستی',
                'value' => $model->zipCode
            ],
            'city' => [
                'label' => 'شهر',
                'value' => $model->getCityName()
            ],
            'state' => [
                'label' => 'استان',
                'value' => $model->getStateName()
            ],
            'country' => [
                'label' => 'کشور',
                'value' => $model->getCountryName()
            ],
            'latitude' => [
                'label' => 'عرض جغرافیایی',
                'value' => $model->latitude
            ],
            'longitude' => [
                'label' => 'طول جغرافیایی',
                'value' => $model->longitude
            ],
            'createAt' => [
                'label' => 'تاریخ ایجاد',
                'value' => $model->createAt
            ],
            'updateAt' => [
                'label' => 'تاریخ ویرایش',
                'value' => $model->updateAt
            ],
        ],
    ]);
    ?>
</p>